sudo: required
services:
  - docker

before_install:
  - docker build -t lexworks/docker-react -f Dockerfile.dev .

script:
  - docker run lexworks/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "bdoreactapp"
  env: "Bdoreactapp-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-792844797253"
  bucket_path: "bdoreactapp"
  on:
    branch: master
  access_key_id: AKIAJMX5RYID5BA2KAIA
  secret_access_key:
    secure: "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"

